# Generated by Django 3.0.2 on 2020-04-13 05:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 4, 13, 5, 1, 10, 332710, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
